version: 1.0
provider:
  name: openfaas
  gateway: https://gw-faas.ornell.io
functions:
  fun1:
    lang: csharp
    handler: ./fun1
    image: rogeralsing/fun1:latest

  fun3:
    lang: aspnet
    handler: ./fun3
    image: rogeralsing/fun3:latest
